language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "6"
  - "8"
  - "node"

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js